/*
 * Hero - Shoutcast and Icecast Radio Player With History - v3.4
 * Copyright 2017-2020, LambertGroup
 *
 */

 (function(f){function M(a,b,d,e){f(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:b.playlistRecordBgOnColor,"border-bottom-color":b.playlistRecordBottomBorderOnColor,color:b.playlistRecordTextOnColor});a.is_very_first||Q(-1,a,b,d);if(""!=b.radio_stream)var p=b.radio_stream;return p}function Y(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);b.send();console.log(a+"   ----   "+b.status);return 404!=b.status}function Z(a,b,d,e){var p=b.noImageAvailable,m="",w="";if(""!=a&&void 0!=a){m=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];
 if("jpg"==m||"jpeg"==m||"JPG"==m||"JPEG"==m)w="&iiurlparam=qlow-1000px";f.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+w,{},function(n){""!=f("ii",n).attr("thumburl")&&void 0!=f("ii",n).attr("thumburl")?(p=f("ii",n).attr("thumburl"),d.wiki_photo_path=p):""!=f("ii",n).attr("url")&&void 0!=f("ii",n).attr("url")&&(p=f("ii",n).attr("url"),d.wiki_photo_path=p);S(b,d,e,p)})}}function T(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,h,g){var u=
 d.noImageAvailable,k="",x="";if(""!=d.optional_images_path)b.playlist_images_arr[g]=a;else if(""!=a&&void 0!=a){k=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==k||"jpeg"==k||"JPG"==k||"JPEGs"==k)x="&iiurlparam=qlow-200px";f.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+x,{},function(A){""!=f("ii",A).attr("thumburl")&&void 0!=f("ii",A).attr("thumburl")?u=f("ii",A).attr("thumburl"):""!=f("ii",A).attr("url")&&void 0!=f("ii",
 A).attr("url")&&(u=f("ii",A).attr("url"));b.playlist_images_arr[g]=u})}0!==(g+1)%3&&g!=b.playlist_arr.length-1||setTimeout(function(){N(b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,h)},1E3)}function R(a){var b;a=a.split("");a.forEach(function(d,e){b="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(d);
 -1!=b&&(a[e]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[b])});return a.join("").trim()}function O(a,b){var d=new XMLHttpRequest;d.open(a.method,"https://zet.pluginsandthemes.ro/"+a.url);d.onload=d.onerror=function(){b(a.method+" "+a.url+"\n"+d.status+" "+d.statusText+"\n\n"+(d.responseText||""))};/^POST/i.test(a.method)&&(d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.setRequestHeader("X-Requested-With","XMLHttpRequest"));d.send(a.data)}function U(a,
 b,d,e,p,m,w,n,q,y,r,t,v,C,z,B){""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),a.playlist_images_arr.pop()),b.grabLastFmPhoto||(a.prev_song_image=b.noImageAvailable),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),N(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B)),a.prevTitle=a.curTitle)}function P(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B){if(b.showOnlyPlayButton||
 a.isRadiojar||""!=b.azuracast_api_nowplaying_url)a.isRadiojar&&O({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/now_playing/?my_rand="+Math.random()},function(g){startPoint=g.indexOf("{");-1!==startPoint&&(lengthPoint=g.length,g=g.substr(startPoint,lengthPoint),g=JSON.parse(g),a.curTitle=g.artist+" - "+g.title,J(a,b,d,m,w,n,q,y,r,t,v),U(a,b,m,d,e,p,C,w,n,q,y,r,t,v,z,B))}),""!=b.azuracast_api_nowplaying_url&&O({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+
 Math.random()},function(g){var u=g.indexOf("{");if(-1!==u){var k=g.length;g=g.substr(u,k);g=JSON.parse(g);a.curTitle=g.now_playing.song.text;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,m,w,n,q,y,r,t,v);U(a,b,m,d,e,p,C,w,n,q,y,r,t,v,z,B)}});else{if(""!=b.metadata_file_type||""!=b.azuracast_api_nowplaying_url)if(a.now_playing_found=!0,a.now_playing_current_k=b.metadata_file_type-1,""==a.ip||void 0==a.ip)a.ip=1;!1===a.now_playing_found&&a.now_playing_current_k<a.now_playing_arr_lenght&&
 a.now_playing_current_k++;var h=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"?my_rand="+Math.random():"");0===a.now_playing_current_k&&(h=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"&my_rand="+Math.random():""));""!=b.url_custom_metdata_file&&(h=b.url_custom_metdata_file);""!=a.ip&&a.now_playing_current_k<a.now_playing_arr_lenght?
 (O({method:"GET",url:h},function(g){var u="";switch(a.now_playing_current_k){case 0:if(-1!=g.indexOf("<SONGTITLE>")){a.now_playing_found=!0;var k=g.indexOf("<SONGTITLE>")+11;var x=g.indexOf("</SONGTITLE>")-k;u=g.substr(k,x);a.curTitle=u;a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim();J(a,b,d,m,w,n,q,y,r,t,v)}else P(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B);break;case 1:k=g.indexOf("<body>")+6;x=g.length;g=g.substr(k,x);g=g.replace("</body></html>","");u=g.split(",");""!=u[6]&&void 0!=u[6]&&"oracle:0"!=
 u[6]?(a.now_playing_found=!0,u=u[6],a.curTitle=u,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,q,y,r,t,v)):P(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B);break;case 2:k=g.indexOf('{"icestats":');if(-1!==k){x=g.length;g=g.substr(k,x);g=JSON.parse(g);k=!1;for(var A=0;A<Object.keys(g.icestats.source).length&&!k;)x=g.icestats.source[A].listenurl,0<x.indexOf(a.mount_point)&&(k=!0,A--),A++;k&&""!=g.icestats.source[A].title&&void 0!=g.icestats.source[A].title&&(a.now_playing_found=!0,u=g.icestats.source[A].title,
 a.curTitle=u,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,q,y,r,t,v))}""==u&&(a.now_playing_found=!1,P(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B));break;case 3:""!=a.mount_point&&(k=g.indexOf(a.mount_point));0<k&&(x=g.length,g=g.substr(k,x));x=g.indexOf("Currently playing:");-1==x&&(x=g.indexOf("Current Song:"));0<x&&(a.now_playing_found=!0,k=g.indexOf('<td class="streamstats">',x),k=0<k?k+24:g.indexOf('<td class="streamdata">',x)+23,x=g.indexOf("</td>",k),u=g.substr(k,x-k),a.curTitle=
 u,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,q,y,r,t,v));""==u&&(a.now_playing_found=!1,P(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B));break;default:a.now_playing_found=!0,a.curTitle="Not available...",a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,q,y,r,t,v)}}),U(a,b,m,d,e,p,C,w,n,q,y,r,t,v,z,B)):(curSong="Data not available...",a.curTitle=curSong,a.curTitle=a.curTitle.replace(/(\r?\n|\r)/gm," ").trim(),J(a,b,d,m,w,n,q,y,r,t,v))}}function V(a,b,d,e,p,m,w,
 n,q,y,r,t,v,C,z,B,h){b.grabLastFmPhoto&&(a.musicbrainzHistory_setTimeout_arr[h]=setTimeout(function(){var g=a.playlist_arr[h].split("-");g[0]=g[0].trim();a.the_artist_id_history_arr[h]="";a.the_wikidata_id_history_arr[h]="";var u=b.noImageAvailable;a.wiki_photo_path=u;clearTimeout(a.musicbrainzHistory_setTimeout_arr[h]);g[0]=g[0].trim();if(""!=b.optional_images_path){var k=b.optional_images_path+a.playlist_arr[h]+".jpg";k=encodeURI(k);k=k.replace("(","%28");k=k.replace(")","%29");k=k.replace("&apos;",
 "%27");k=k.replace("&amp;","%26");Y(k)||(k=b.noImageAvailable);T(k,a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B,h)}else f.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+g[0],{},function(x){var A="",c,l="";a.the_artist_id_history_arr[h]="";var E=g[0];E=E.toLowerCase();E=R(E);f("artist",x).each(function(){c=f("name",this)[0];0<f("name",this).length&&""==a.the_artist_id_history_arr[h]&&(A=f(c).text(),A=A.toLowerCase(),A=R(A),E.toLowerCase()==A.toLowerCase()&&(a.the_artist_id_history_arr[h]=f(this).attr("id")))});
 ""==a.the_artist_id_history_arr[h]&&"ROCK RADIO"!=g[0]&&(a.the_artist_id_history_arr[h]=f(f("artist",x)[0]).attr("id"));""!=a.the_artist_id_history_arr[h]&&void 0!=a.the_artist_id_history_arr[h]&&(a.musicbrainzHistory_setTimeout_arr[h]=setTimeout(function(){a.the_wikidata_id_history_arr[h]="";f.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id_history_arr[h]+"?inc=url-rels",{},function(G){f("relation",G).each(function(){"image"==f(this).attr("type")&&0<f("target",this).length&&(l=f("target",
 this).text(),l=l.substr(l.indexOf("File:",10)+5,l.length),T(l,a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B,h));"wikidata"==f(this).attr("type")&&0<f("target",this).length&&""==l&&(a.the_wikidata_id_history_arr[h]=f("target",this).text(),a.the_wikidata_id_history_arr[h]=a.the_wikidata_id_history_arr[h].substr(a.the_wikidata_id_history_arr[h].indexOf("/Q",10)+1,a.the_wikidata_id_history_arr[h].length),f.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id_history_arr[h]+"&property=P18&format=xml&origin=*",
 {},function(H){l=f("datavalue",f("mainsnak",H)).attr("value");T(l,a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B,h)}))});if(""==l||void 0==l)a.playlist_images_arr[h]=u})},3E3*(h+1)))})},3E3*(h+1)))}function ea(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,h){clearInterval(a.radioReaderAjaxInterval);if(-1!==b.radio_stream.indexOf("radiojar.com")){a.isRadiojar=!0;var g=b.radio_stream.match(a.myregexp_radiojar);null!=g&&(a.http_or_https=g[1],a.ip=g[2],a.mount_point=g[3],a.port="")}else-1==b.radio_stream.indexOf("/",9)&&(b.radio_stream+=
 "/;"),"/"==b.radio_stream.charAt(b.radio_stream.length-1)&&(b.radio_stream+=";"),g=b.radio_stream.match(a.myregexp),null!=g&&(a.http_or_https=g[1],a.ip=g[2],a.port=g[3],a.mount_point=g[4],";"==a.mount_point.trim()&&(a.mount_point=""));r.css({width:b.playerWidth+"px",height:b.imageHeight+"px",background:"url("+b.noImageAvailable+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});if(!b.showOnlyPlayButton){P(a,b,d,v,t,e,p,m,w,n,q,y,r,C,z,B);a.radioReaderAjaxInterval=
 setInterval(function(){P(a,b,d,v,t,e,p,m,w,n,q,y,r,C,z,B)},1E3*b.nowPlayingInterval);a.playlist_arr=[];a.playlist_images_arr=[];var u=-1,k,x,A,c=0;a.isRadiojar&&O({method:"GET",url:"http://www.radiojar.com/api/stations/"+a.mount_point+"/tracks/?my_rand="+Math.random()},function(l){k=l.indexOf("[{");if(-1!==k){x=l.length;l=l.substr(k,x);var E=JSON.parse(l);E.reverse()}for(c=0;c<Object.keys(E).length;c++)""!=E[c].track&&"Empty Title"!=E[c].track&&(u++,a.playlist_arr[u]=E[c].artist+" - "+E[c].track,
 a.playlist_images_arr[u]=b.noImageAvailable,V(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,u));a.playlist_arr.length?N(a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&h.click()});""!=b.azuracast_api_nowplaying_url&&O({method:"GET",url:b.azuracast_api_nowplaying_url+"?my_rand="+Math.random()},function(l){k=l.indexOf("{");if(-1!==k){x=l.length;l=l.substr(k,x);l=JSON.parse(l);for(c=0;c<Object.keys(l.song_history).length;c++)""!=l.song_history[c].song.text&&"Empty Title"!=l.song_history[c].song.text.text&&
 (u++,a.playlist_arr[u]=l.song_history[c].song.text,a.playlist_images_arr[u]=b.noImageAvailable,V(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,u));a.playlist_arr.length?N(a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&h.click()}});a.isRadiojar||""!=b.azuracast_api_nowplaying_url||b.iceCastFirst||O({method:"GET",url:a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.history_arr[a.history_current_k]},function(l){if(-1!=l.indexOf("Current Song"))for(k=l.indexOf("Current Song")+12,x=l.length,
 l=l.substr(k,x),A=l.split("</td><td>"),A.shift(),l=0;l<A.length;l++)k=A[l].indexOf("</"),-1!=k&&(x=k,A[l]=A[l].substr(0,x),A[l]=A[l].replace(/<\/?[^>]+(>|$)/g,""),""!=A[l]&&"Empty Title"!=A[l]&&(u++,a.playlist_arr[u]=A[l],a.playlist_arr[u]=a.playlist_arr[u].replace(/(\r?\n|\r)/gm," ").trim(),a.playlist_images_arr[u]=b.noImageAvailable,V(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,u)));a.playlist_arr.length?N(a,b,e,d,v,t,C,p,m,w,n,q,y,r,z,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&h.click()})}a.isFlashNeeded?
 ""!=a.myFlashObject&&a.myFlashObject.myAS3function(M(a,b,d,e),b.initialVolume):(document.getElementById(a.audioID).src=M(a,b,d,e),document.getElementById(a.audioID).load(),b.autoPlay&&p.click())}function S(a,b,d,e){d.css({background:"url("+e+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});b.prev_song_image=b.cur_song_image;b.cur_song_image=e}function J(a,b,d,e,p,m,w,n,q,y,r){a.curSongText="";b.showTitle&&null!=a.curTitle&&""!=a.curTitle&&
 (a.curSongText+=a.curTitle);b.showRadioStation&&null!=b.radio_name&&""!=b.radio_name&&q.html(b.radio_name);var t=a.curTitle.split("-"),v=b.noImageAvailable;t[0]=t[0].trim();3<=t.length&&(t[0]=t[0].trim()+"-"+t[1].trim());if(b.grabLastFmPhoto&&""!=t[0].trim()){var C,z="",B,h="";a.the_artist_id="";a.the_wikidata_id="";v=b.noImageAvailable;a.wiki_photo_path=v;clearTimeout(a.musicbrainz_setTimeout);clearTimeout(a.no_artist_image_setTimeout);t[0]=t[0].trim();""!=t[0]&&void 0!=t[0]&&a.prevTitle!=a.curTitle&&
 (r.css({background:"url("+v+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"}),a.musicbrainz_setTimeout=setTimeout(function(){""!=b.optional_images_path?(h=b.optional_images_path+a.curTitle+".jpg",h=encodeURI(h),h=h.replace("(","%28"),h=h.replace(")","%29"),h=h.replace("&apos;","%27"),h=h.replace("&amp;","%26"),Y(h)||(h=b.noImageAvailable),v=h,S(b,a,r,v)):f.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+t[0],{},function(g){a.the_artist_id=
 "";C=t[0];C=C.toLowerCase();C=R(C);f("artist",g).each(function(){B=f("name",this)[0];0<f("name",this).length&&""==a.the_artist_id&&(z=f(B).text(),z=z.toLowerCase(),z=R(z),C.toLowerCase()==z.toLowerCase()&&(a.the_artist_id=f(this).attr("id")))});""==a.the_artist_id&&"ROCK RADIO"!=t[0]&&(a.the_artist_id=f(f("artist",g)[0]).attr("id"));""!=a.the_artist_id&&void 0!=a.the_artist_id&&(a.musicbrainz_setTimeout=setTimeout(function(){a.the_wikidata_id="";f.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id+
 "?inc=url-rels",{},function(u){f("relation",u).each(function(){"image"==f(this).attr("type")&&0<f("target",this).length&&(h=f("target",this).text(),h=h.substr(h.indexOf("File:",10)+5,h.length),Z(h,b,a,r));"wikidata"==f(this).attr("type")&&0<f("target",this).length&&""==h&&(a.the_wikidata_id=f("target",this).text(),a.the_wikidata_id=a.the_wikidata_id.substr(a.the_wikidata_id.indexOf("/Q",10)+1,a.the_wikidata_id.length),f.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id+
 "&property=P18&format=xml&origin=*",{},function(k){h=f("datavalue",f("mainsnak",k)).attr("value");Z(h,b,a,r)}))});a.no_artist_image_setTimeout=setTimeout(function(){""!=h&&void 0!=h||S(b,a,r,v)},1E3)})},1500))})},1500))}a.curSongText&&(d=a.curSongText.split("-"),a.curSongAuthorText=d[0].trim(),2<=d.length&&(a.curSongText=d[1].trim()),3<=d.length&&(a.curSongAuthorText=d[0].trim()+"-"+d[1].trim(),a.curSongText=d[2].trim()),m.html(aa(a.curSongAuthorText,b)),n.css({width:"auto"}),a.isStationTitleInsideScrolling=
 !1,a.stationTitleInsideWait=0,n.stop(),n.css({"margin-left":0}),n.html(a.curSongText),clearInterval(a.timeupdateInterval),n.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&n.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,n.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),n.css({"margin-left":0}),n.stop().animate({"margin-left":b.playerWidth-
 n.width()+"px"},parseInt(1E4*(n.width()-b.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&n.width()>a.titleWidth&&a.stationTitleInsideWait++},300):n.css({width:"100%"}))}function Q(a,b,d,e){if(b.gen_total_images>d.numberOfThumbsPerScreen){var p=(b.thumbsHolder_ThumbHeight+1)*(b.gen_total_images-d.numberOfThumbsPerScreen),m=0;e.stop(!0,!0);f("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){w.preventDefault()});
 -1==a||b.isCarouselScrolling?!b.isCarouselScrolling&&b.gen_total_images>d.numberOfThumbsPerScreen&&(b.isCarouselScrolling=!0,m=-1*parseInt((b.thumbsHolder_ThumbHeight+1)*b.current_img_no,10),Math.abs(m)>p&&(m=-1*p),b.gen_total_images>d.numberOfThumbsPerScreen&&d.showPlaylist&&b.audio6_html5_sliderVertical.slider("value",100+parseInt(100*m/p)),e.animate({top:m+"px"},500,"easeOutCubic",function(){b.isCarouselScrolling=!1;f("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){})})):
 (b.isCarouselScrolling=!0,m=2>=a?-1*p:parseInt(p*(a-100)/100,10),0<m&&(m=0),e.animate({top:m+"px"},1100,"easeOutQuad",function(){b.isCarouselScrolling=!1;f("html, body").off("touchstart touchmove").on("touchstart touchmove",function(w){})}))}}function W(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B,h,g,u,k,x,A,c,l,E,G){e.width(d.playerWidth);if(d.showOnlyPlayButton||b.isMinified)a="none";"none"==a?z.css({width:"0px",height:"0px"}):z.css({width:d.playerWidth+"px",height:parseInt(d.playerWidth/d.origWidth*d.imageHeight,
 10)+"px"});d.sticky&&d.startMinified?z.css({display:"none",top:"0px",left:"0px"}):z.css({display:a,top:"0px",left:"0px"});b.imageTopPos=0;b.imageLeftPos=0;b.frameBehindTextTopPos=z.height();b.frameBehindTextLeftPos=0;d.showOnlyPlayButton?g.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,width:0,height:0}):g.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:d.frameBehindTextColor,height:q.height()+2*b.playVerticalPadding+
 "px"});b.playTopPos=b.frameBehindTextTopPos+b.playVerticalPadding;b.playLeftPos=b.frameBehindTextLeftPos+b.playHorizontalPadding;q.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});b.titleWidth=d.playerWidth-4*b.playHorizontalPadding-q.width();b.titleTopPos=b.playTopPos+3;b.titleLeftPos=q.width()+2*b.playHorizontalPadding;r.css({color:d.songTitleColor,top:b.titleTopPos+"px",left:b.titleLeftPos+"px",width:b.titleWidth+"px"});b.lineSeparatorTopPos=b.titleTopPos+r.height()+2;b.lineSeparatorLeftPos=
 b.titleLeftPos;u.css({background:d.lineSeparatorColor,top:b.lineSeparatorTopPos+"px",left:b.lineSeparatorLeftPos+"px",width:b.titleWidth+"px"});b.authorTopPos=b.lineSeparatorTopPos+8;b.authorLeftPos=b.titleLeftPos;y.css({color:d.authorTitleColor,top:b.authorTopPos+"px",left:b.authorLeftPos+"px",width:b.titleWidth+"px"});b.minimizeTopPos=b.playTopPos;!d.sticky||d.showOnlyPlayButton?(b.minimizeRightPos=0,x.css({display:"none",padding:0,margin:0})):d.sticky&&(b.minimizeRightPos=b.smallButtonDistance,
 x.css({top:b.minimizeTopPos+"px",right:b.minimizeRightPos+"px"}));b.frameBehindButtonsTopPos=b.frameBehindTextTopPos+g.height();b.frameBehindButtonsLeftPos=0;d.showOnlyPlayButton?k.css({background:d.frameBehindButtonsColor,height:0,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"}):k.css({background:d.frameBehindButtonsColor,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"});b.radioStationTopPos=b.frameBehindButtonsTopPos+Math.floor(k.height()-v.height())/
 2;b.radioStationLeftPos=b.playHorizontalPadding;v.css({color:d.radioStationColor,top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px",width:b.titleWidth+"px"});0==b.historyButWidth&&(b.historyButWidth=A.width());b.showhidehistoryTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-A.height())/2);b.temp_showHistoryBut?(b.showhideplaylistRightPos=2*b.smallButtonDistance,A.css({display:"block",width:b.historyButWidth+"px",top:b.showhidehistoryTopPos+"px",right:b.showhideplaylistRightPos+
 "px"})):(b.showhideplaylistRightPos=0,A.css({display:"none",width:0,padding:0,margin:0}));c.css({display:"none",width:0,padding:0,margin:0});b.volumeTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-l.height())/2);d.showVolume?(b.volumeRightPos=b.showhideplaylistRightPos+A.width()+b.smallButtonDistance,l.css({top:b.volumeTopPos+"px",right:b.volumeRightPos+"px"})):(b.volumeRightPos=b.showhideplaylistRightPos+A.width(),l.css({display:"none",width:0,padding:0,margin:0}));b.twitterTopPos=b.frameBehindButtonsTopPos+
 Math.floor((k.height()-E.height())/2);d.showTwitterBut?(b.twitterRightPos=b.volumeRightPos+l.width()+b.smallButtonDistance,E.css({top:b.twitterTopPos+"px",right:b.twitterRightPos+"px"})):(b.twitterRightPos=b.volumeRightPos+l.width(),E.css({display:"none",width:0,padding:0,margin:0}));b.facebookTopPos=b.frameBehindButtonsTopPos+Math.floor((k.height()-G.height())/2);d.showFacebookBut?(b.facebookRightPos=b.twitterRightPos+E.width()+b.smallButtonDistance,G.css({top:b.facebookTopPos+"px",right:b.facebookRightPos+
 "px"})):(b.facebookRightPos=b.twitterRightPos,G.css({display:"none",width:0,padding:0,margin:0}))}function N(a,b,d,e,p,m,w,n,q,y,r,t,v,C,z,B){if(!b.showOnlyPlayButton){e.stop(!0,!0);a.isCarouselScrolling=!1;f(".readingData",m).css({display:"none"});n=parseInt(b.playerWidth/b.origWidth*b.historyRecordTitleLimit,10);q=parseInt(b.playerWidth/b.origWidth*b.historyRecordAuthorLimit,10);y=[];a.isHistoryGenerated=!0;e.html("");for(r=a.gen_total_images=0;r<a.playlist_arr.length;r++)a.gen_total_images++,y=
 a.playlist_arr[r].split("-"),1>y.length?a.gen_total_images--:(a.thumbsHolder_Thumb=f('<div class="thumbsHolder_ThumbOFF" rel="'+(a.gen_total_images-1)+'" data-origID="'+r+'"><div class="padding"><div class="img_div" style="background-image:url('+a.playlist_images_arr[r]+');background-color:#000000;"></div><span class="titlex">'+ba(y[1],n,b)+'</span><span class="authorx">'+ba(y[0],q,b)+"</span></div></div>"),e.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=
 a.thumbsHolder_Thumb.height()),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.gen_total_images+"px",background:b.historyRecordBgColor,"border-bottom-color":b.historyRecordBottomBorderColor,color:b.historyRecordTextColor}),f(".titlex",a.thumbsHolder_Thumb).css({color:b.historyRecordSongColor,"border-bottom-color":b.historyRecordSongBottomBorderColor}),f(".authorx",a.thumbsHolder_Thumb).css({color:b.historyRecordAuthorColor}),a.current_img_no=0);p.height(2*b.historyPadding+(a.thumbsHolder_ThumbHeight+
 1)*b.numberOfThumbsPerScreen+B.height()+b.historyPadding);m.height((a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen);m.css({"margin-top":B.height()+b.historyPadding+"px"});w.css({padding:b.historyPadding+"px"});a.thumbsHolder_Thumbs=f(".thumbsHolder_ThumbOFF",d);a.wrapperHeight=a.audioPlayerHeight+p.height()+b.historyTopPos;if(!b.showHistory||!b.showHistoryOnInit||0>p.css("margin-top").substring(0,p.css("margin-top").length-2))a.wrapperHeight=a.audioPlayerHeight;a.isMinified||z.css({height:a.wrapperHeight+
 "px"});a.gen_total_images>b.numberOfThumbsPerScreen&&b.showHistory?(b.isPlaylistSliderInitialized&&a.audio6_html5_sliderVertical.slider("destroy"),a.audio6_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(h,g){Q(g.value,a,b,e)}}),b.isPlaylistSliderInitialized=!0,a.audio6_html5_sliderVertical.css({display:"inline",position:"absolute",height:p.height()-20-3*b.historyPadding-B.height()+"px",left:d.width()-a.audio6_html5_sliderVertical.width()-
 b.historyPadding+"px",top:a.audioPlayerHeight+b.historyTopPos+2*b.historyPadding+2+B.height()+"px"}),b.showHistoryOnInit||a.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),f(".thumbsHolder_ThumbOFF",d).css({width:d.width()-a.audio6_html5_sliderVertical.width()-2*b.historyPadding-3+"px"})):(b.isPlaylistSliderInitialized&&(a.audio6_html5_sliderVertical.slider("destroy"),b.isPlaylistSliderInitialized=!1),f(".thumbsHolder_ThumbOFF",d).css({width:d.width()-2*b.historyPadding+"px"}));m.mousewheel(function(h,
 g,u,k){h.preventDefault();h=a.audio6_html5_sliderVertical.slider("value");if(1<parseInt(h)&&-1==parseInt(g)||100>parseInt(h)&&1==parseInt(g))h+=3*g,a.audio6_html5_sliderVertical.slider("value",h),Q(h,a,b,e)});e.css({top:"0px"})}}function aa(a,b){b.preserveOriginalUpperLowerCase||(a=a.toLowerCase(),a=a.replace(/\b[a-z]/g,function(d){return d.toUpperCase()}),a=a.replace(/&Apos;/gi,"'"),a=a.replace(/&Amp;/gi,"&"),a=a.replace(/'[A-Z]/g,function(d){return d.toLowerCase()}));return a}function ba(a,b,d){a=
 String(a);var e="";if(a.length>b){a=a.substring(0,b);var p=a.split(" ");a=a.substring(b-2,b-1);""!=a&&(p.pop(),e="...");a=p.join(" ")}a=aa(a,d);return a+e}function fa(){f("audio").each(function(){f(".AudioPlay").removeClass("AudioPause");f(this)[0].pause()})}function ca(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,d=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=d.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,d=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,
 null!=d.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function ha(a){var b=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||(b=!0);return b}var K=navigator.userAgent.toLowerCase();f.fn.audio6_html5=function(a){a=f.extend({},f.fn.audio6_html5.defaults,a);ca();return this.each(function(){var b=f(this),d=f('<div class="frameBehindText"></div><div class="frameBehindButtons"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioCloseBut" title="Minimize"></a><a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="songAuthorLineSeparator"></div>  <div class="songAuthor"></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="historyPadding">  <div class="historyTitle"></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 e=b.parent(".audio6_html5");e.addClass(a.skin);e.append(d);var p=f(".frameBehindText",e),m=f(".frameBehindButtons",e);f(".AudioControls",e);var w=f(".AudioFacebook",e),n=f(".AudioTwitter",e),q=f(".AudioPlay",e),y=f(".AudioShowHidePlaylist",e),r=f(".VolumeButton",e),t=f(".VolumeSlider",e),v=f(".AudioCloseBut",e),C=f(".songTitle",e),z=f(".songTitleInside",e),B=f(".songAuthor",e),h=f(".songAuthorLineSeparator",e),g=f(".radioStation",e),u=f(".ximage",e),k=f(".historyTitle",e);e.wrap("<div class='the_wrapper'></div>");
 var x=e.parent(),A=ca();if(-1!=K.indexOf("ipad")||-1!=K.indexOf("iphone")||-1!=K.indexOf("ipod")||-1!=K.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;e.css({background:"transparent"});var c={current_img_no:0,origID:0,is_very_first:!0,total_images:0,gen_total_images:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",playlist_images_arr:"",isCarouselScrolling:!1,isHistoryGenerated:!1,isStationTitleInsideScrolling:!1,curTitle:"",prevTitle:"",cur_song_image:"",
 prev_song_image:"",curSongText:"",curSongAuthorText:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,wrapperHeight:0,temp_showHistoryBut:!0,historyButWidth:0,isRadiojar:!1,historyInitialHeight:90,thumbsHolder_Thumb:f('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",constantDistance:0,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,titleTopPos:0,titleLeftPos:0,lineSeparatorTopPos:0,lineSeparatorLeftPos:0,
 authorTopPos:0,authorLeftPos:0,minimizeTopPos:0,minimizeRightPos:0,isMinified:!1,imageTopPos:0,imageLeftPos:0,frameBehindButtonsTopPos:0,frameBehindButtonsLeftPos:0,frameBehindTextTopPos:0,frameBehindTextLeftPos:0,playTopPos:0,playLeftPos:0,volumeTopPos:0,volumeRightPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhidehistoryTopPos:0,showhideplaylistRightPos:0,smallButtonDistance:4,playVerticalPadding:10,playHorizontalPadding:16,facebookTopPos:0,facebookRightPos:0,twitterTopPos:0,twitterRightPos:0,
 origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioID:"",audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,myregexp:/^(http|https):\/\/(.*):(.*)\/(.*)$/,myregexp_radiojar:/^(http|https):\/\/(.*)\/(.*)$/,http_or_https:"http",ip:"",port:"",mount_point:"",now_playing_current_k:-1,now_playing_found:!1,now_playing_arr_lenght:0,
 now_playing_arr:["stats?sid=1","7.html","status-json.xsl","status.xsl"],history_current_k:0,history_arr:["played.html"],the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",no_artist_image_setTimeout:"",the_artist_id_history_arr:[""],the_wikidata_id_history_arr:[""],musicbrainzHistory_setTimeout_arr:[""],wiki_photo_path:a.noImageAvailable};a.iceCastFirst&&(c.now_playing_current_k=1,c.isHistoryGenerated=!0);a.preserveOriginalUpperLowerCase||(z.css({"text-transform":"uppercase"}),B.css({"text-transform":"capitalize"}));
 a.sticky||(a.startMinified=!1);30>a.nowPlayingInterval&&(a.nowPlayingInterval=44);a.showOnlyPlayButton&&(a.startMinified=!1,a.showFacebookBut=!1,a.showVolume=!1,a.showTwitterBut=!1,a.showRadioStation=!1,a.showTitle=!1,a.showHistoryBut=!1,a.showHistory=!1,a.playerWidth=q.width()+2*c.playHorizontalPadding,a.historyPadding=0);a.origWidth=a.playerWidth;c.temp_showHistoryBut=a.showHistoryBut;c.now_playing_arr_lenght=Object.keys(c.now_playing_arr).length;c.audioID=b.attr("id");-1==(-1==navigator.userAgent.indexOf("Opera")&&
 navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));c.isFlashNeeded=ha(c);-1!=A&&(c.isFlashNeeded=!0);c.isFlashNeeded=!1;a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v3.2",status:!0,cookie:!0,xfbml:!0})},function(D,F,I){var L=D.getElementsByTagName(F)[0];
 D.getElementById(I)||(D=D.createElement(F),D.id=I,D.src="//connect.facebook.com/en_US/sdk.js",L.parentNode.insertBefore(D,L))}(document,"script","facebook-jssdk"),w.on("click",function(){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":document.URL,"og:title":a.facebookShareTitle,"og:description":a.facebookShareDescription,"og:image":a.facebookShareImage}})},function(D){})}));if(a.showTwitterBut)n.on("click",function(){window.open("https://twitter.com/intent/tweet?url="+
 document.URL+"&text="+a.radio_name,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});W("block",c,a,e,H,l,G,E,q,B,C,z,g,b,u,x,k,p,h,m,v,y,t,r,n,w);c.audioPlayerHeight=u.height()+p.height()+m.height();a.showOnlyPlayButton&&(c.audioPlayerHeight=q.height()+2*c.playVerticalPadding);e.height(c.audioPlayerHeight);if(a.startMinified||a.showOnlyPlayButton)c.historyInitialHeight=0;c.wrapperHeight=c.audioPlayerHeight+c.historyInitialHeight+a.historyTopPos;a.showHistory&&
 a.showHistoryOnInit||(c.wrapperHeight=c.audioPlayerHeight);x.css({border:a.playerBorderSize+"px solid "+a.playerBorderColor,width:e.width()+"px",height:c.wrapperHeight+"px"});a.centerPlayer&&x.css({margin:"0 auto"});var l=f(".thumbsHolderWrapper",e),E=f(".historyPadding",e),G=f(".thumbsHolderVisibleWrapper",e),H=f(".thumbsHolder",e);c.audio6_html5_sliderVertical=f(".slider-vertical",e);E.css({padding:a.historyPadding+"px"});G.append('<div class="readingData">'+a.translateReadingData+"</div>");k.width(a.playerWidth-
 2*a.historyPadding);k.html(a.historyTranslate);k.css({color:a.historyTitleColor});a.showHistory||l.css({opacity:0});a.showHistoryOnInit||l.css({opacity:0,"margin-top":"-20px"});l.css({width:e.width()+"px",top:c.audioPlayerHeight+a.historyTopPos+"px",left:"0px",background:a.historyBgColor});G.width(e.width());a.sticky&&(x.addClass("audio6_html5_sticky_div"),v.on("click",function(){var D=500;if(c.isMinified){c.isMinified=!1;v.removeClass("AudioOpenBut");var F="block";c.temp_showHistoryBut=a.showHistoryBut;
 c.audioPlayerHeight=parseInt(a.playerWidth/a.origWidth*a.imageHeight,10)+p.height()+m.height();var I=0>l.css("margin-top").substring(0,l.css("margin-top").length-2)?c.audioPlayerHeight:c.audioPlayerHeight+l.height()+a.historyTopPos}else c.isMinified=!0,v.addClass("AudioOpenBut"),F="none",c.audioPlayerHeight=p.height()+m.height(),I=c.audioPlayerHeight,c.temp_showHistoryBut=!1;W(F,c,a,e,H,l,G,E,q,B,C,z,g,b,u,x,k,p,h,m,v,y,t,r,n,w);u.css({display:F});a.startMinified?(D=0,a.startMinified=!1):D=500;l.css({display:F,
 top:c.audioPlayerHeight+a.historyTopPos+"px"});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({display:F,top:c.audioPlayerHeight+a.historyTopPos+2*a.historyPadding+2+k.height()+"px"});x.animate({height:I},D,"easeOutQuad",function(){})}));t.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(D,F){a.initialVolume=F.value;c.isFlashNeeded?c.myFlashObject.myAS3function(M(c,a,H,e),a.initialVolume):document.getElementById(c.audioID).volume=
 F.value},stop:function(D,F){}});document.getElementById(c.audioID).volume=a.initialVolume;t.css({background:a.volumeOffColor});f(".ui-slider-range",t).css({background:a.volumeOnColor});q.on("click",function(){var D=c.isFlashNeeded?!q.hasClass("AudioPause"):document.getElementById(c.audioID).paused;fa();0==D?(c.isFlashNeeded?c.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(c.audioID).pause(),q.removeClass("AudioPause")):(c.isFlashNeeded?c.myFlashObject.myAS3function("_play_radio_stream_",
 a.initialVolume):(document.getElementById(c.audioID).src=M(c,a,H,e),document.getElementById(c.audioID).load(),document.getElementById(c.audioID).play()),q.addClass("AudioPause"))});y.on("click",function(){if(0>l.css("margin-top").substring(0,l.css("margin-top").length-2)){var D=1;var F="block";var I="0px";var L=c.audioPlayerHeight+l.height()+a.historyTopPos;l.css({display:F});c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:1,display:"block"})}else D=0,F="none",
 I="-20px",c.gen_total_images>a.numberOfThumbsPerScreen&&c.audio6_html5_sliderVertical.css({opacity:0,display:"none"}),L=c.audioPlayerHeight;l.css({"z-index":-1});l.animate({opacity:D,"margin-top":I},500,"easeOutQuad",function(){l.css({display:F,"z-index":"auto"})});x.animate({height:L},500,"easeOutQuad",function(){})});r.on("click",function(){document.getElementById(c.audioID).muted?(document.getElementById(c.audioID).muted=!1,r.removeClass("VolumeButtonMuted"),c.isFlashNeeded&&(a.initialVolume=c.prevVolumeVal,
 c.myFlashObject.myAS3function(M(c,a,H,e),a.initialVolume))):(document.getElementById(c.audioID).muted=!0,r.addClass("VolumeButtonMuted"),c.isFlashNeeded&&(c.prevVolumeVal=a.initialVolume,a.initialVolume=0,c.myFlashObject.myAS3function(M(c,a,H,e),a.initialVolume)))});l.swipe({swipeStatus:function(D,F,I,L,ja,ka){"up"!=I&&"down"!=I||0==L||(currentScrollVal=c.audio6_html5_sliderVertical.slider("value"),currentScrollVal="up"==I?currentScrollVal-1.5:currentScrollVal+1.5,c.audio6_html5_sliderVertical.slider("value",
 currentScrollVal),f("html, body").off("touchstart touchmove").on("touchstart touchmove",function(ia){ia.preventDefault()}),Q(currentScrollVal,c,a,H))},threshold:100,maxTimeThreshold:500,fingers:"all",allowPageScroll:"none",preventDefaultEvents:!1});c.isFlashNeeded&&(c.rndNum=parseInt(998999*Math.random()+1E3),e.append("<div id='swfHolder"+c.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){c.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+
 a.radio_stream+"&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},"swfHolder"+c.rndNum)}),a.autoPlay&&q.addClass("AudioPause"));ea(c,a,H,e,q,B,C,z,g,b,u,G,l,E,x,k,v);-1==K.indexOf("ipad")&&-1==K.indexOf("iphone")&&-1==K.indexOf("ipod")&&-1==K.indexOf("webos")||q.removeClass("AudioPause");var da=function(){""==c.origParentFloat&&(c.origParentFloat=e.parent().css("float"),c.origParentPaddingTop=e.parent().css("padding-top"),c.origParentPaddingRight=e.parent().css("padding-right"),c.origParentPaddingBottom=
 e.parent().css("padding-bottom"),c.origParentPaddingLeft=e.parent().css("padding-left"));a.playerWidth!=a.origWidth||a.playerWidth>f(window).width()?e.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):e.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft});var D=e.parent().parent().width();if(e.width()!=
 D){a.playerWidth=a.origWidth>D?D:a.origWidth;if(e.width()!=a.playerWidth){W("block",c,a,e,H,l,G,E,q,B,C,z,g,b,u,x,k,p,h,m,v,y,t,r,n,w);c.audioPlayerHeight=u.height()+p.height()+m.height();c.isMinified&&(c.audioPlayerHeight=p.height()+m.height());e.height(c.audioPlayerHeight);c.wrapperHeight=c.audioPlayerHeight+l.height()+a.historyTopPos;if(!a.showHistory||!a.showHistoryOnInit||c.isMinified||0>l.css("margin-top").substring(0,l.css("margin-top").length-2))c.wrapperHeight=c.audioPlayerHeight;x.css({width:e.width()+
 "px",height:c.wrapperHeight+"px"});k.width(a.playerWidth-2*a.historyPadding);l.css({width:e.width()+"px",top:c.audioPlayerHeight+a.historyTopPos+"px"});G.width(e.width());N(c,a,e,H,l,G,E,q,B,C,z,g,b,u,x,k)}a.playerWidth<f(window).width()&&e.parent().css({"float":c.origParentFloat,"padding-top":c.origParentPaddingTop,"padding-right":c.origParentPaddingRight,"padding-bottom":c.origParentPaddingBottom,"padding-left":c.origParentPaddingLeft})}},X=!1;f(window).on("resize",function(){var D=!0;-1!=A&&9==
 A&&0==c.windowWidth&&(D=!1);c.windowWidth==f(window).width()?(D=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,D=!0)):c.windowWidth=f(window).width();a.responsive&&D&&(!1!==X&&clearTimeout(X),X=setTimeout(function(){da()},300))});a.responsive&&da()})};f.fn.audio6_html5.defaults={radio_stream:"http://194.232.200.150:80/;",radio_name:"Idobi Anthm",url_custom_metdata_file:"",metadata_file_type:"",playerWidth:335,imageHeight:335,
 skin:"whiteControllers",initialVolume:1,autoPlay:!0,loop:!0,playerBg:"#000000",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#ffffff",authorTitleColor:"#ffffff",lineSeparatorColor:"#636363",radioStationColor:"#ffffff",frameBehindTextColor:"#000000",frameBehindButtonsColor:"#454545",playerBorderSize:0,playerBorderColor:"#000000",sticky:!1,startMinified:!1,showOnlyPlayButton:!1,centerPlayer:!1,iceCastFirst:!1,showFacebookBut:!0,facebookAppID:"",facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",
 facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",facebookShareImage:"",showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showHistoryBut:!0,showHistory:!0,showHistoryOnInit:!0,translateReadingData:"reading history...",historyTranslate:"HISTORY - latest played songs",historyTitleColor:"#858585",historyTopPos:0,historyBgColor:"#ebebeb",historyRecordBgColor:"transparent",historyRecordBottomBorderColor:"transparent",
 historyRecordSongColor:"#000000",historyRecordSongBottomBorderColor:"#d0d0d0",historyRecordAuthorColor:"#6d6d6d",numberOfThumbsPerScreen:3,historyPadding:16,preserveOriginalUpperLowerCase:!1,responsive:!0,historyRecordTitleLimit:25,historyRecordAuthorLimit:36,nowPlayingInterval:35,grabLastFmPhoto:!0,optional_images_path:"",azuracast_api_nowplaying_url:"",azuracast_get_image:!1,pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,
 isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
